#!/bin/sh

# TODO: Objective of this script: Centralise media control for music

radio=("https://youtu.be/5qap5aO4i9A;Lofi Girl"
       "https://youtu.be/5yx6BWlEVcY;Chillhop"
       "https://youtu.be/l7TxwBhtTUY;The Bootleg Boy"
       "https://youtu.be/I83XWCSBgSc;Radio Spinner")

radio_url=("https://youtu.be/5qap5aO4i9A"
           "https://youtu.be/5yx6BWlEVcY"
           "https://youtu.be/l7TxwBhtTUY"
           "https://youtu.be/I83XWCSBgSc")

playlist=("John Wick Music")
playlist_url=("https://youtube.com/playlist?list=PLoF6yioKKKUV0Uo3lnKmdfw-PpQLTPhKo")

video=()
video_url=()

mpv_args="--no-video --volume=30"
rofi_menu_command="rofi -dmenu -no-lazy-grab -theme theme/appmenu.rasi | cut -d. -f1"

notification(){
    notify-send "En cours de lecture: " "$@" --icon=media-tape
}

menu_main(){
    printf "1. Radio\n"
    printf "2. Playlist\n"
    printf "3. Video\n"
}

menu(){
    case ${1} in
        "radio")
            array=("${radio[@]}")
            ;;
        "playlist")
            array=("${playlist[@]}")
            ;;
        "video")
            array=("${video[@]}")
            ;;
        *) "Unknown menu";;
    esac
    IFS=';' read -ra selected <<< "$array"
    echo ${selected}
    # IFS='||' read -ra array <<< "${radio}"
    # for i in "${array[@]}"; do
    #     readarray -d , -t line<<<${1}
    #     # for w in line; do
    #     # done
    #     echo "${line[0]}"
    # done
    # for (( i=0; i<${#array[@]}; i++ ));
    # do
    #     printf "$((i + 1)). ${radio[$i]}\n"
    # done
}

launch_menu(){
    choice=$("menu" ${1} | ${rofi_menu_command})
    # play_music "${array[${choice}]}" "${array_url[${choice}]}"
}

# play the selected music
# ${1} = Name
# ${2} = URL
play_music(){


    notification ${1};
    notification ${2};
    # run mpv with args and selected url
    # added title arg to make sure the pkill command kills only this instance of mpv
    # mpv ${mpv_args} --title="radio-mpv" ${2}
}

main() {
    launch_menu radio
}

main
# pkill -f radio-mpv || main
