#!/usr/bin/env sh

rofi_command="rofi -theme theme/powermenu.rasi"

### Options ###
power_off=" Eteindre"
reboot=" Redemarrer"
lock=" Verrouiller"
suspend=" Hiberner"
log_out=" Deconnexion"
# Variable passed to rofi
options="$power_off\n$reboot\n$lock\n$suspend\n$log_out"

condition=$(echo -e "$options" | $rofi_command -dmenu -selected-row 2)

case $condition in
    $power_off)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        echo "lock"
        ;;
    $suspend)
        # dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
        systemctl suspend
        ;;
    $log_out)
        echo "awesome.quit()" | awesome-client
        ;;
esac
