#!/usr/bin/env bash

INSTALL_PACKAGES=1
INSTALL_FSTAB=1
INSTALL_AUR=1
INSTALL_FLATPAKS=1
ENABLE_MULTILIB=1
PARALLEL_DOWNLOADS=0

SCRIPTS=(
  "configure_zsh"
  "configure_git"
  "configure_lightdm"
  "configure_vm"
  "configure_keyboard"
  "configure_dconf"
  "configure_bluetooth"
  "configure_cups"
  "install_reflector"
  "install_dotfiles"
)

PACKAGES=(
  # Git
  "git-lfs"

  # Pacman related packages for AUR
  "base-devel"
  "pacman-contrib"
  "reflector"
  "starship"

  # CPU & GPU drivers
  "amd-ucode"
  "xf86-video-amdgpu"
  "xf86-video-ati"
  "mesa"
  "lib32-mesa"
  "vulkan-radeon"
  "lib32-vulkan-radeon"
  "libva-mesa-driver"
  "lib32-libva-mesa-driver"
  "libva-mesa-driver"
  "mesa-vdpau"
  "lib32-mesa-vdpau"

  "lightdm"
  "lightdm-gtk-greeter"
  "gnome-themes-extra"

  # Fonts packages
  "gnu-free-fonts"
  "ttf-jetbrains-mono"
  "ttf-jetbrains-mono-nerd"
  "noto-fonts-emoji"
  "ttf-bitstream-vera"
  "ttf-croscore"
  "ttf-dejavu"
  "ttf-droid"
  "ttf-ibm-plex"
  "ttf-liberation"
  "ttf-linux-libertine"
  "noto-fonts"
  "ttf-font-awesome"

  "polkit"
  "polkit-gnome"

  # Display server & display manager packages
  "xorg-server"
  "xorg-xrandr"
  "xorg-xsetroot"
  "xorg-xprop"
  "numlockx"
  "xcb-util-cursor"
  "picom"

  # Audio
  "alsa-utils"
  "alsa-oss"
  "pipewire"
  "pipewire-alsa"
  "pipewire-pulse"
  "pavucontrol"

  # Network management
  "nm-connection-editor"
  "network-manager-applet"
  "gufw"
  "bluez"
  #"blueman"

  # Printers
  "cups"
  "cups-filters"
  "cups-pdf"
  "system-config-printer"
  "imagescan"

  # Archive
  "unzip"
  "unrar"
  "unace"
  "lrzip"
  "squashfs-tools"

  # Terminal
  "alacritty"
  "zsh"
  "zsh-completions"
  "zsh-syntax-highlighting"
  "zsh-autosuggestions"

  "stow"

  # WM
  "sxhkd"
  "awesome"
  
  # DE
  plasma

  # Apps
  "less"
  "nitrogen"
  "rofi"
  "gammastep"
  "dunst"
  "xclip"
  "maim"
  "slurp"
  "libqalculate"
  "openssh"
  "converseen"
  "btop"
  "radeontop"
  "neofetch"
  "onefetch"
  "yt-dlp"
  "flatpak"
  "gitui"
  "easyeffects"
  "calf"
  "fcitx5-im"
  "fcitx5-anthy"
  "fcitx5-mozc"
  "obs-studio"

  # Mouse
  "libratbag"
  "piper"

  # Browser
  "firefox"
  "firefox-i18n-fr"

  # Graphics
  "imv"
  "gimp"
  "inkscape"
  "blender"
  "mpv"
  "syncplay"
  "pyside"

  # File Manager
  "gvfs"
  "gvfs-smb"
  "gvfs-mtp"
  "tumbler"
  "ffmpegthumbnailer"
  "nemo" # gsettings set org.cinnamon.desktop.default-applications.terminal exec alacritty
  "nemo-fileroller"
  "file-roller"

  # Office
  "libreoffice-fresh"
  "libreoffice-fresh-fr"

  # Editor
  "neovim"
  "ripgrep"
  "fd"

  # Game Engine
  "godot"
  "python"
  "scons"

  "docker"
  "docker-compose"

  "rustup"

  # .NET
  "dotnet-host"
  "dotnet-runtime"
  "dotnet-sdk"
  "dotnet-targeting-pack"
  "mono-msbuild"

  # Java
  "jdk-openjdk"
  "jre-openjdk"

  "npm"

  # Gaming
  "wine-staging"
  "giflib"
  "lib32-giflib"
  "libpng"
  "lib32-libpng"
  "libldap"
  "lib32-libldap"
  "gnutls"
  "lib32-gnutls"
  "mpg123"
  "lib32-mpg123"
  "openal"
  "lib32-openal"
  "v4l-utils"
  "lib32-v4l-utils"
  "libpulse"
  "lib32-libpulse"
  "libgpg-error"
  "lib32-libgpg-error"
  "alsa-plugins"
  "lib32-alsa-plugins"
  "alsa-lib"
  "lib32-alsa-lib"
  "libjpeg-turbo"
  "lib32-libjpeg-turbo"
  "sqlite"
  "lib32-sqlite"
  "libxcomposite"
  "lib32-libxcomposite"
  "libxinerama"
  "lib32-libgcrypt"
  "libgcrypt"
  "lib32-libxinerama"
  "ncurses"
  "lib32-ncurses"
  "opencl-icd-loader"
  "lib32-opencl-icd-loader"
  "libxslt"
  "lib32-libxslt"
  "libva"
  "lib32-libva"
  "gtk3"
  "lib32-gtk3"
  "gst-plugins-base-libs"
  "lib32-gst-plugins-base-libs"
  "vulkan-icd-loader"
  "lib32-vulkan-icd-loader"
  "vkd3d"
  "lib32-vkd3d"

  "gamemode"
  "gamescope"

  # Virtual Machine
  "qemu-full"
  "libvirt"
  "edk2-ovmf"
  "virt-manager"
  "dnsmasq"
  "ebtables"
)

AUR=(
  # Apps
  "swww"
  "picom-jonaburg-git"
  "joshuto"
  "feishin-bin"

  # Themes
  "bibata-cursor-theme"
  "catppuccin-gtk-theme-mocha"
  "dracula-gtk-theme"
  "dracula-icons-git"

  # Printer drivers
  "epson-inkjet-printer-escpr"
  "epson-inkjet-printer-escpr2"

  "opencl-amd"
)

FLATPAKS=(
  "net.lutris.Lutris"
  "com.github.tchx84.Flatseal"
  "io.freetubeapp.FreeTube"
  "com.logseq.Logseq"
  "com.valvesoftware.Steam"
  "org.freedesktop.Platform.VulkanLayer.MangoHud"
  "org.freedesktop.Platform.VulkanLayer.gamescope"
  "com.github.Matoking.protontricks"
  "io.itch.itch"
  "io.github.RodZill4.Material-Maker"
  "io.github.achetagames.epic_asset_manager"
  "org.gtk.Gtk3theme.adw-gtk3-dark"
)

FLATPAK_GTK_THEME="adw-gtk2-dark"
FLATPAK_APPLY_THEME=(
  "io.freetubeapp.FreeTube"
  "info.beyondallreason.bar"
  "com.valvesoftware.Steam"
  "org.godotengine.Godot"
)

FSTAB=(
  "b1b44759-b1a5-47c7-8019-d70d67099a1b -> /mnt/PERSO -> defaults,nofail -> ext4"
  "86aaa5e6-f8d3-4886-bf3e-c804c8559e6c -> /mnt/PRO -> defaults,nofail,noauto,x-gvfs-show -> ext4"
  "541e75e3-db7a-4367-a8d5-6d230e853faf -> /mnt/GAMES -> defaults,nofail -> ext4"
  "d7bbe9d8-4f98-4d87-b26a-34c75907f71a -> /mnt/DATA -> defaults,nofail -> ext4"
  "83e09479-85e0-45e1-82a3-217add68fe9e -> /mnt/HOT -> defaults,nofail -> ext4"
  "035c8d2e-41d7-49e1-8cb4-ae950a53b06f -> /mnt/VM -> defaults,nofail,noauto,x-gvfs-show -> ext4"
  "45b03bfe-40d7-45e4-8839-59792ca9fd9a -> /mnt/NEH -> defaults,nofail,noauto,x-gvfs-show -> ext4"
)

DCONF=(
  "/org/gnome/desktop/interface/font-name = Cantarell 10"
  "/org/gnome/desktop/interface/document-font-name = Cantarell 10"
  "/org/gnome/desktop/interface/gtk-theme = Dracula"
  "/org/gnome/desktop/interface/icon-theme = Dracula"
  "/org/gnome/desktop/interface/cursor-theme = Bibata-Original-Classic"
  "/org/gnome/desktop/interface/cursor-size = 16"
  "/org/gnome/desktop/interface/font-hinting = full"
  "/org/gnome/desktop/interface/font-antialiasing = rgba"

  # Disable middle-click paste
  "/org/gnome/desktop/interface/gtk-enable-primary-paste = false"
  "/org/gnome/desktop/wm/preferences/theme = Dracula"
  # Remove min-max-close buttons
  "/org/gnome/desktop/wm/preferences/button-layout = "

  # Disable events sounds
  "/org/gnome/desktop/sound/event-sounds = false"
  "/org/gnome/desktop/sound/input-feedback-sounds = false"

# Disable recent files
  "/org/gnome/desktop/privacy/remember-recent-files = false"
  "/org/gnome/desktop/privacy/remember-recent-files/recent-files-max-age = 0"
)

# Creates every profile
FIREFOX_PROFILES=(
  "normal"
  "work"
  "social"
)
