#!/usr/bin/env bash

print_message "Installing spaceship..."

# Clone and build Spaceship
git clone https://aur.archlinux.org/spaceship-prompt-git.git --depth=1 "${INSTALL_DIRECTORY}/spaceship" \
    && cd "${INSTALL_DIRECTORY}/spaceship" \
    && makepkg -si --noconfirm --needed

# Making the cache directory for zsh
mkdir -p ${HOME}/.cache/zsh

print_inner_message "Setting ZSH as the default shell"
sudo chsh -s /bin/zsh ${USER}

print_inner_message "Updating grub configuration"
sudo grub-mkconfig -o /boot/grub/grub.cfg
