#!/usr/bin/env bash

print_message "Configuring Virtual Machine"

sudo pacman --noconfirm -Rns iptables
sudo systemctl enable --now libvirtd
sudo virsh net-start default
sudo virsh net-autostart default
sudo usermod -aG kvm,input,libvirt quentin
