#!/usr/bin/env bash

GRUB_RESOLUTION="2560x1080"
GRUB_OPTIONS="--boot --theme vimix --screen ultrawide"

print_message "Configuring grub..."

doas sed -i -e "s/GRUB_GFXMODE=auto/GRUB_GFXMODE=$GRUB_RESOLUTION,auto/g" /etc/default/grub
git clone https://github.com/vinceliuice/grub2-themes "${INSTALL_DIRECTORY}/grub2-themes"
doas ./install.sh ${GRUB_OPTIONS}

doas grub-mkconfig -o /boot/grub/grub.cfg
