#!/usr/bin/env bash

print_message "Configuring AUR related packages"

git clone https://aur.archlinux.org/paru.git "${INSTALL_FOLDER}/paru"
cd "${INSTALL_FOLDER}/paru"
makepkg -si --noconfirm --needed
