#!/usr/bin/bash

print_message "Installing LTS Kernel..."

doas linux-lts
print_inner_message "Updating grub configuration..."
doas grub-mkconfig -o /boot/grub/grub.cfg

# Change boot order
local grub_boot_list=$(sudo grep gnulinux /boot/grub/grub.cfg)
local grub_submenu=$(echo $grub_boot_list | sed -r "s/^.*(gnulinux-advanced-[a-zA-Z0-9-]*).*/\1/")
local grub_arch=$(echo $grub_boot_list | sed -r "s/^.*(gnulinux-linux-advanced-[a-zA-Z0-9-]*).*/\1/")
local grub_boot="GRUB_DEFAULT=\"$grub_submenu>$grub_arch\""

doas sed -i -r "s/^GRUB_DEFAULT=0/#GRUB_DEFAULT=0\n$grub_boot/" /etc/default/grub
doas grub-mkconfig -o /boot/grub/grub.cfg
