#!/usr/bin/env bash

print_message "Installing DWM"

git clone --recurse-submodules https://gitlab.com/dev.quentinfranchi/dwm "${INSTALL_DIRECTORY}/dwm"
cd "${INSTALL_DIRECTORY}/dwm"
./dwm-config --install || print_error "Unable to install DWM"
