#!/usr/bin/env bash

print_message "Installing pacman packages"
for package in "${PACKAGES[@]}"; do
    pacman_install $package || print_message "Could not install package: $package"
done

if [ ${INSTALL_AUR} -eq 1 ]; then
    print_inner_message "Installing AUR packages..."
    for package in "${AUR[@]}"; do
        aur_install $package || print_error "Could not install AUR package: $package"
    done
fi

if [ ${INSTALL_FLATPAKS} -eq 1 ]; then
    print_inner_message "Installing Flatpaks..."
    for flatpak in "${FLATPAKS[@]}"; do
        flatpak install -y $flatpak || print_error "Could not install flatpak: $flatpak"
    done
fi

# errors=()
# for package in "${PACKAGES[@]}"; do
#     doas pacman -S --needed --noconfirm $package || errors+=($package)
# done

# # Check for errors
# if [ ${#errors[@]} -gt 0 ]; then
#     echo "Packages not installed:" > ./config_apps.log
#     for package in "${errors[@]}"; do
#         echo $package > ./config_apps.log
#     done
# fi
# errors=()


# # Check for errors
# if [ ${#errors[@]} -gt 0 ]; then
#     echo "Packages not installed:" > ./config_apps.log
#     for package in "${errors[@]}"; do
#         echo $package > ./config_apps.log
#     done
# fi
install_firefox_gnome_theme
