#!/usr/bin/env bash

# Installs Window Manager packages

dotfiles_root_directory="/opt/dotfiles"

print_inner_message "Installing user dotfiles"
cd stow_home && stow * || print_error "Unable to install dotfiles"

print_inner_message "Installing root dotfiles"

# Check
[ -d /usr/share/xsessions ] || doas mkdir /usr/share/xsessions
[[ -d "${dotfiles_root_directory}_temp" ]] && doas rm -rf "${dotfiles_root_directory}_temp"

# move and install root part of the dotfiles
doas git clone https://gitlab.com/dev.quentinfranchi/dotfiles "${dotfiles_root_directory}_temp" \
    && doas mv "${dotfiles_root_directory}_temp/stow_root" "${dotfiles_root_directory}" \
    && doas rm -rf "${dotfiles_root_directory}_temp" \
    && cd "${dotfiles_root_directory}"

for directory in $( ls -p | grep / ); do
    CONFLICTS=$(stow --no --verbose ${directory} 2>&1 | awk '/\* existing target is/ {print $NF}')
    for f in ${CONFLICTS[@]}; do
        [[ -f "/${f}" || -L "/${f}" ]] && sudo rm "/${f}"
    done
done
doas stow * || print_error "Unable to install dotfiles"
