#!/usr/bin/env bash

pacman_install reflector

# Enable automatic mirrors update
sudo systemctl enable reflector.timer
sudo systemctl start reflector.timer

# Update mirrors right now
sudo systemctl start reflector.service
