#!/usr/bin/env bash

pacman_install reflector

# Enable automatic mirrors update
doas systemctl enable reflector.timer
doas systemctl start reflector.timer

# Update mirrors right now
doas systemctl start reflector.service
