#!/usr/bin/env bash

# Installs Window Manager packages

print_inner_message "Installing user dotfiles"
cd stow_home && stow * || print_error "Unable to install dotfiles"

print_inner_message "Installing root dotfiles"

# Check
[ -d /usr/share/xsessions ] || sudo mkdir /usr/share/xsessions
[[ -d "${DOTFILES_ROOT_DIRECTORY}_temp" ]] && sudo rm -rf "${dotfiles_root_directory}_temp"

# move and install root part of the dotfiles
sudo git clone https://github.com/dev.quentinfranchi/dotfiles "${DOTFILES_ROOT_DIRECTORY}_temp" \
    && sudo mv "${DOTFILES_ROOT_DIRECTORY}_temp/stow_root" "${dotfiles_root_directory}" \
    && sudo rm -rf "${DOTFILES_ROOT_DIRECTORY}_temp" \
    && cd "${DOTFILES_ROOT_DIRECTORY}"

for directory in $( ls -p | grep / ); do
    CONFLICTS=$(stow --no --verbose ${directory} 2>&1 | awk '/\* existing target is/ {print $NF}')
    for f in ${CONFLICTS[@]}; do
        [[ -f "/${f}" || -L "/${f}" ]] && sudo rm "/${f}"
    done
done
sudo stow * || print_error "Unable to install dotfiles"
