#!/usr/bin/env bash

# Wanna have some juicy printers working?
sudo systemctl enable cups

# Hello from the TTY, i would like to have a GUI please
sudo systemctl enable lightdm

sudo systemctl enable --now libvirtd

# Enable automatic mirrors update
sudo systemctl enable reflector.timer
sudo systemctl start reflector.timer

# Update mirrors right now
sudo systemctl start reflector.service
