#!/usr/bin/env sh

rofi_command="rofi -theme theme/powermenu.rasi"

### Options ###
power_off="\tEteindre"
reboot="\tRedémarrer"
lock="\tVérrouiller"
suspend="\tHiberner"
log_out="\tDéconnexion"
# Variable passed to rofi
options="$power_off\n$reboot\n$lock\n$suspend\n$log_out"

case "$(echo -e "$options" | $rofi_command -dmenu -selected-row 2)" in
    $power_off)
        systemctl poweroff
        ;;
    $reboot)
        systemctl reboot
        ;;
    $lock)
        echo "zzz"
        ;;
    $suspend)
        dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
        systemctl suspend
        ;;
    $log_out)
        echo "awesome.quit()" | awesome-client
        ;;
esac
